### ISSUE TITLE
Error when running the node 'rosidl_typesupport_c' for package 'splsm_7

### ISSUE THREAD

**Issue by limenutt** [ros-sports/r2r_spl#26] opened 2022-09-29 00:57 UTC
I've followed the installation guide from the documentation, then run 
`ros2 run r2r_spl_7 r2r_spl --ros-args -p team_num:=0 -p player_num:=1`

Here is the full output

```
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 46, in import_type_support
    return importlib.import_module(module_name, package=pkg_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /opt/ros/foxy/lib/libsplsm_7__rosidl_generator_c.so: undefined symbol: rosidl_runtime_c__uint8__Sequence__are_equal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/r2r_spl_7/r2r_spl", line 11, in <module>
    load_entry_point('r2r-spl-7==0.0.2', 'console_scripts', 'r2r_spl')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/r2r_spl_7/r2r_spl.py", line 97, in main
    r2r_spl = R2RSPL()
  File "/opt/ros/foxy/lib/python3.8/site-packages/r2r_spl_7/r2r_spl.py", line 52, in __init__
    self._publisher = self.create_publisher(SPLSM, 'r2r/recv', 10)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/node.py", line 1140, in create_publisher
    check_for_type_support(msg_type)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/type_support.py", line 29, in check_for_type_support
    msg_type.__class__.__import_type_support__()
  File "/opt/ros/foxy/lib/python3.8/site-packages/splsm_7/msg/_splsm.py", line 34, in __import_type_support__
    module = import_type_support('splsm_7')
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/import_type_support_impl.py", line 48, in import_type_support
    raise UnsupportedTypeSupport(pkg_name)
rosidl_generator_py.import_type_support_impl.UnsupportedTypeSupport: Could not import 'rosidl_typesupport_c' for package 'splsm_7'
```

When I run `ros2 pkg prefix rosidl_typesupport_c`
I get `/opt/ros/foxy` so it seems that the package is there

**Comment by ijnek** [comment] 2022-09-29 01:50
I can't reproduce the issue, my one runs fine. Have you sourced your ROS 2 installation? Also, check that all of your ROS 2 packages are up-to-date (upgraded)

**Comment by ijnek** [comment] 2022-09-29 01:53
Seems related: https://github.com/ros2/examples/issues/303

**Comment by limenutt** [comment] 2022-09-29 22:55
It has been indeed solved by `sudo apt upgrade` however, whouldn't the correct dependencies' versions were specified in this package in the first place?

**Comment by ijnek** [comment] 2022-09-30 01:20
I haven't made a new release for r2r_spl since the 9th of August, so assuming you installed r2r_spl after that, I believe there must have been an issue in a further upstream package (like rosidl_runtime_c), and was fixed in a release since you last installed that package.

Btw, ROS can't support specifying dependency versions like PyPI can. But maintainers tend to try and keep API/ABI 
 compatible within a distro, so it is strange that you faced that problem. My tip would be to always keep your packages upgraded.

**Comment by ijnek** [comment] 2022-09-30 01:21
Closing, as I don't believe this is an issue with this repository.

**Closed as completed by ijnek** 2022-09-30 01:21 UTC
